name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm i .
    - name: Run tests
      run: SKIP_PREFLIGHT_CHECK=true npm test
    - name: Build
      run: |
        SKIP_PREFLIGHT_CHECK=true npm run build
        mv build/* .
        rm -rf build/
        git rm -rf src/ cv/ public/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "Github: update build files"
    - name: Push changes to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        force: true
