name: Build

on:
  push:
    branches:
      - testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm i .
    - name: Run tests and make coverage
      run: npm run test-coverage
    - name: Send test coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.info
    - name: Build
      run: |
        npm run build
    #     mv build/* .
    #     rm -rf build/
    #     git rm -rf src/ cv/ public/
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add --all
    #     git commit -m "Deploy build files from testing"
    # - name: Push changes to master
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GIT_TOKEN }}
    #     force: true
